site_name: "Колибри - термоанализ"
nav:
  - 'О приборе': index.md
  - 'ПО': software.md
  - 'Характеристики': characteristics.md
  - 'Примеры измерений': examples.md
#  - 'Документация': docs.md
  - 'Контакты': contacts.md
theme:
  name: material
  custom_dir: overrides
  language: ru
  icon:
    logo: material/fire
  favicon: assets/favicon/favicon.ico
  palette:
    scheme: default
    primary: light blue
    accent: deep purple
  features:
    - navigation.tabs
plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: true
      effect: zoom
      width: 90%
      height: auto
      zoomable: true
markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - md_in_html
  - attr_list
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - css/extra.css